services:
  web:
    build: .
    container_name: rfid-web
    depends_on:
      - chirpstack
    environment:
      SECRET_KEY: ${SECRET_KEY}
      LORA_WEBHOOK_SECRET: ${LORA_WEBHOOK_SECRET}
      SQLALCHEMY_DATABASE_URI: sqlite:////app/instance/database.db
    volumes:
      - ./instance:/app/instance
      - ./data:/app/data
    ports:
      - "5001:5000"
    restart: unless-stopped

  chirpstack:
    image: chirpstack/chirpstack:4
    container_name: chirpstack
    depends_on: [postgres, redis, mosquitto]
    command: ["--config", "/etc/chirpstack"]
    volumes:
      - ./chirpstack-config:/etc/chirpstack
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped

  postgres:
    image: timescale/timescaledb:2.13.1-pg15
    container_name: chirpstack-postgres
    environment:
      POSTGRES_DB: chirpstack
      POSTGRES_USER: chirpstack
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - chirpstack-pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chirpstack -d chirpstack"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: chirpstack-redis
    command: ["redis-server", "--save", "60", "1000", "--loglevel", "warning"]
    volumes:
      - chirpstack-redis:/data
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: chirpstack-mosquitto
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883"
    restart: unless-stopped

volumes:
  chirpstack-pg:
  chirpstack-redis:
  mosquitto-data:
  mosquitto-log: