services:
  web:
    build: .
    container_name: rfid-web
    environment:
      SECRET_KEY: ${SECRET_KEY}
      LORA_WEBHOOK_SECRET: ${LORA_WEBHOOK_SECRET}
      SQLALCHEMY_DATABASE_URI: sqlite:////app/instance/database.db
    volumes:
      - ./instance:/app/instance
      - ./data:/app/data
    ports:
      - "5001:5000"
    restart: unless-stopped


  serial-reader:
    build:
      context: .
      dockerfile: serial/Dockerfile
    environment:
      - SERIAL_URL=socket://host.docker.internal:2001
      - INGEST_URL=http://web:5000/api/ingest
      - SERIAL_TIMEOUT=0.2
      - DEBUG=1
    depends_on:
      - web
    restart: unless-stopped

    