services:
  web:
    build: .
    container_name: rfid-web
    environment:
      SECRET_KEY: ${SECRET_KEY}
      LORA_WEBHOOK_SECRET: ${LORA_WEBHOOK_SECRET}
      SQLALCHEMY_DATABASE_URI: sqlite:////app/instance/database.db
    volumes:
      - ./instance:/app/instance
      - ./data:/app/data
    ports:
      - "5001:5000"
    restart: unless-stopped


  serial-reader:
    build: .
    command: ["python", "-u", "serial/serial_reader.py"]
    environment:
      SERIAL_PORT: socket://socat:2001
      BAUDRATE: "115200"
      API_URL: http://web:5000/api/ingest
    restart: unless-stopped