"""add hide_gps_map to competition

Revision ID: 09113cfb4396
Revises: c8c7404f63fa
Create Date: 2026-04-12 16:23:43.490793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09113cfb4396'
down_revision: Union[str, None] = 'c8c7404f63fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_gps_map', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_column('hide_gps_map')

    # ### end Alembic commands ###
